game:
  languages: ['de', 'en']
  defaultLanguage: de
  canSwitchQuests: false
  duration: 480
  maxActiveQuests: 100
  cameraPresets:
    walking:
      offset:
        x: 0
        y: -1.35
      zoom: 0.65
    talking:
      offset:
        x: 0
        y: -0.8
      zoom: 1
    drone:
      offset:
        x: 0
        y: 0
      zoom: 0.5
textures:
  bundles:
    - name: 'town-view'
      assets:
        - name: 'town-bg'
          srcs: 'kaufloft.png'
        - name: 'town-collmap'
          srcs: 'kaufloft-collmap.png'
        - name: 'player-1'
          srcs: 'player-1.json'
        - name: 'player-2'
          srcs: 'player-2.json'
        - name: 'player-3'
          srcs: 'player-3.json'
        - name: 'npcs-demo'
          srcs: 'npcs-demo.json'
        - name: 'mood-balloon'
          srcs: 'mood-balloon.json'
        - name: 'map-markers'
          srcs: 'map-markers.json'
        - name: 'icons'
          srcs: 'icons.json'
        - name: 'target-arrow'
          srcs: 'target-arrow.png'
        - name: 'guide-arrow'
          srcs: 'guide-arrow.png'
        - name: 'protesters'
          srcs: 'protesters.png'
        - name: 'activistTent'
          srcs: 'activist-tent.png'
        - name: 'storeMural'
          srcs: 'store-mural.png'
        - name: 'bandStage'
          srcs: 'band-stage.png'
        - name: 'storeApts'
          srcs: 'store-apts.png'
        - name: 'greenRoof'
          srcs: 'green-roof.png'
        - name: 'storesPractical'
          srcs: 'stores-practical.png'
        - name: 'storesLuxury'
          srcs: 'stores-luxury.png'
        - name: 'boardedDoors'
          srcs: 'boarded-doors.png'
        - name: 'comingSoon'
          srcs: 'coming-soon.png'
        - name: 'bandDrum'
          srcs: 'band-drum.png'
        - name: 'bandKeyboard'
          srcs: 'band-keyboard.png'
        - name: 'bandGuitar'
          srcs: 'band-guitar.png'
        - name: 'bandVoiceM'
          srcs: 'band-voice-m.png'
        - name: 'bandVoiceF'
          srcs: 'band-voice-f.png'
        - name: 'ringlight'
          srcs: 'ringlight.png'
        - name: 'camera'
          srcs: 'camera.png'
        - name: 'statue'
          srcs: 'statue.png'
players:
  1:
    color: '#43f56e'
    spawn: { x: 3041, y: 2947 }
  2:
    color: '#625eff'
    spawn: { x: 3212, y: 2947 }
  3:
    color: '#db6bf8'
    spawn: { x: 3383, y: 2640 }
storylines:
  - kaufloft
i18n:
  ui:
    pressStart:
      en: "Press the button to start"
      de: "Start mit Knopfdruck"
    defaultPrompt:
      en: 'Help revive the neighborhood. Talk to citizens with a :speech_bubble: to get quests.'
      de: 'Hilf, das Viertel wiederzubeleben.<br>Sprich mit Bürger:innen mit einer&nbsp;:speech_bubble:, um Aufgaben zu erhalten.'
    decisionMade:
      en: ''
      de: ''
#    title:
#      en: 'Data 🩷 Quest'
#    pressStart:
#      en: "Press space to start"
#    decisionMade:
#      en: 'Thank you for playing! Here are your quest achievements:'
#    waitingToBegin:
#      en: 'Get ready! A new game will begin soon.'
#    waitingToEnd:
#      en: 'Waiting for the other players…'
#    pressToContinue:
#      en: 'Press space to continue'
#    includedInDecision:
#      en: 'Included in the decision'
#    inclusionBarTitle:
#      en: 'Who decides?'



